spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  h2:
    console:
      enabled: true

custom.password.pattern: '^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{8,}$'
